site_name: Alert Manager
site_author: Simon Balz <simon@balz.me>, Mika Borner <mika.borner@gmail.com>
pages:
    - Introduction: index.md
    - Installation: installation_manual.md
    - Update: update_manual.md
    - Configuration: configuration_manual.md
    - User Manual: user_manual.md
    - Reference: reference.md
    - Release Notes: release_notes.md
    - FAQ: faq.md
    - About: about.md
theme: readthedocs
