site_name: Alert Manager
pages:
    - Introduction: index.md
    - Deploy and Configure: installation_manual.md
    - User Manual: user_manual.md
    - Reference: reference.md
    - Release Notes: release_notes.md
    - FAQ: faq.md
    - About: about.md
theme: readthedocs    